FROM ubuntu:14.04

MAINTAINER Leo Fischer

RUN apt-get update
RUN apt-get install -y vim wget curl git python3 python3-pip

#setup ubuntu user
RUN useradd -ms /bin/bash ubuntu
RUN echo "ubuntu:sudo" | chpasswd
RUN usermod -aG sudo ubuntu
RUN mkdir -p /data/db/
RUN chown ubuntu /data/db
RUN sudo echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ubuntu
ENV HOME /home/ubuntu

RUN echo "set tabstop=2" >> ~/.vimrc
RUN echo "set shiftwidth=2" >> ~/.vimrc
RUN echo "set softtabstop=2" >> ~/.vimrc

#One Time Staging Steps
WORKDIR "/home/ubuntu"

RUN git clone https://github.com/conekta/conekta-python.git
WORKDIR "/home/ubuntu/conekta-python"

#additional python libs
RUN sudo pip3 install -e .

RUN echo "alias python=python3" >> ~/.bashrc
RUN echo "alias pip=pip3" >> ~/.bashrc
